spring.application.name=mobil-app-ws
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/mobil_app_db
spring.jpa.hibernate.ddl-auto=update
